SELECT A.STD_SKU
     , A.PARENT_STD_SKU
     , A.PRODUCT_SUPPLIER
     , A.PRODUCT_NAME
     , A.PRODUCT_SIZE
     , A.PRODUCT_COLOR
     , A.PRODUCT_DESIGN
     , A.PRODUCT_QTY
     , A.PRODUCT_PRICE
  FROM `INVENTORY` A
 ORDER BY A.PARENT_STD_SKU, A.STD_SKU
;

 SELECT A.LISTING_ITEM_ID
      , A.STD_SKU
      , B.MARKET_NAME
      , A.LISTING_SKU
      , A.LISTING_PRODUCT_NAME
      , A.LISTING_PRODUCT_QTY
      , A.LISTING_PRODUCT_PRICE
      , A.LISTING_PRODUCT_FBM
   FROM `LISTING` A
      , (
            SELECT B.MARKET_ID
                 , CONCAT(B.BRAND_NAME, ' ', B.CHANNEL_NAME) AS MARKET_NAME
              FROM `MARKET` B
        ) B
  WHERE A.MARKET_ID = B.MARKET_ID
  ORDER BY 2, 1, 3
;

 SELECT A.LISTING_ITEM_ID
      , B.MARKET_NAME
      , A.LISTING_SKU
      , A.LISTING_PRODUCT_NAME
      , A.LISTING_PRODUCT_SIZE
      , A.LISTING_PRODUCT_COLOR
      , A.LISTING_PRODUCT_QTY
      , A.LISTING_PRODUCT_DESIGN
      , A.LISTING_PRODUCT_PRICE
      , A.LISTING_PRODUCT_FBM
   FROM `UNLINK_LISTING` A
      , (
            SELECT B.MARKET_ID
                 , CONCAT(B.BRAND_NAME, ' ', B.CHANNEL_NAME) AS MARKET_NAME
              FROM `MARKET` B
        ) B
  WHERE A.MARKET_ID = B.MARKET_ID
  ORDER BY 1, 2
;


SELECT A.STD_SKU,
       B.PARENT_STD_SKU,
       B.PRODUCT_NAME AS INVENTORY_PRODUCT_NAME,
       B.PRODUCT_SUPPLIER,
       B.PRODUCT_SIZE,
       B.PRODUCT_COLOR,
       B.PRODUCT_DESIGN,
       MAX(IF (A.MARKET_ID = 1, A.LISTING_SKU, '')) AS HAB_AMAZON_LISTING_SKU,
       MAX(IF (A.MARKET_ID = 1, A.LISTING_ITEM_ID, '')) AS HAB_AMAZON_LISTING_ITEM_ID,
       MAX(IF (A.MARKET_ID = 1, A.LISTING_PRODUCT_NAME, '')) AS HAB_AMAZON_LISTING_PRODUCT_NAME,
       MAX(IF (A.MARKET_ID = 1, A.LISTING_PRODUCT_QTY, '')) AS HAB_AMAZON_LISTING_PRODUCT_QTY,
       MAX(IF (A.MARKET_ID = 1, A.LISTING_PRODUCT_PRICE, '')) AS HAB_AMAZON_LISTING_PRODUCT_PRICE,
       MAX(IF (A.MARKET_ID = 2, A.LISTING_SKU, '')) AS HAB_WALMART_LISTING_SKU,
       MAX(IF (A.MARKET_ID = 2, A.LISTING_ITEM_ID, '')) AS HAB_WALMART_LISTING_ITEM_ID,
       MAX(IF (A.MARKET_ID = 2, A.LISTING_PRODUCT_NAME, '')) AS HAB_WALMART_LISTING_PRODUCT_NAME,
       MAX(IF (A.MARKET_ID = 2, A.LISTING_PRODUCT_QTY, '')) AS HAB_WALMART_LISTING_PRODUCT_QTY,
       MAX(IF (A.MARKET_ID = 2, A.LISTING_PRODUCT_PRICE, '')) AS HAB_WALMART_LISTING_PRODUCT_PRICE,
       MAX(IF (A.MARKET_ID = 8, A.LISTING_SKU, '')) AS HAB_SEARS_LISTING_SKU,
       MAX(IF (A.MARKET_ID = 8, A.LISTING_ITEM_ID, '')) AS HAB_SEARS_LISTING_ITEM_ID,
       MAX(IF (A.MARKET_ID = 8, A.LISTING_PRODUCT_NAME, '')) AS HAB_SEARS_LISTING_PRODUCT_NAME,
       MAX(IF (A.MARKET_ID = 8, A.LISTING_PRODUCT_QTY, '')) AS HAB_SEARS_LISTING_PRODUCT_QTY,
       MAX(IF (A.MARKET_ID = 8, A.LISTING_PRODUCT_PRICE, '')) AS HAB_SEARS_LISTING_PRODUCT_PRICE,
       MAX(IF (A.MARKET_ID = 3, A.LISTING_SKU, '')) AS SHOPIFY_LISTING_SKU,
       MAX(IF (A.MARKET_ID = 3, A.LISTING_ITEM_ID, '')) AS SHOPIFY_LISTING_ITEM_ID,
       MAX(IF (A.MARKET_ID = 3, A.LISTING_PRODUCT_NAME, '')) AS SHOPIFY_LISTING_PRODUCT_NAME,
       MAX(IF (A.MARKET_ID = 3, A.LISTING_PRODUCT_QTY, '')) AS SHOPIFY_LISTING_PRODUCT_QTY,
       MAX(IF (A.MARKET_ID = 3, A.LISTING_PRODUCT_PRICE, '')) AS SHOPIFY_LISTING_PRODUCT_PRICE,
       MAX(IF (A.MARKET_ID = 4, A.LISTING_SKU, '')) AS MC_AMAZON_LISTING_SKU,
       MAX(IF (A.MARKET_ID = 4, A.LISTING_ITEM_ID, '')) AS MC_AMAZON_LISTING_ITEM_ID,
       MAX(IF (A.MARKET_ID = 4, A.LISTING_PRODUCT_NAME, '')) AS MC_AMAZON_LISTING_PRODUCT_NAME,
       MAX(IF (A.MARKET_ID = 4, A.LISTING_PRODUCT_QTY, '')) AS MC_AMAZON_LISTING_PRODUCT_QTY,
       MAX(IF (A.MARKET_ID = 4, A.LISTING_PRODUCT_PRICE, '')) AS MC_AMAZON_LISTING_PRODUCT_PRICE,
       MAX(IF (A.MARKET_ID = 5, A.LISTING_SKU, '')) AS MC_EBAY_LISTING_SKU,
       MAX(IF (A.MARKET_ID = 5, A.LISTING_ITEM_ID, '')) AS MC_EBAY_LISTING_ITEM_ID,
       MAX(IF (A.MARKET_ID = 5, A.LISTING_PRODUCT_NAME, '')) AS MC_EBAY_LISTING_PRODUCT_NAME,
       MAX(IF (A.MARKET_ID = 5, A.LISTING_PRODUCT_QTY, '')) AS MC_EBAY_LISTING_PRODUCT_QTY,
       MAX(IF (A.MARKET_ID = 5, A.LISTING_PRODUCT_PRICE, '')) AS MC_EBAY_LISTING_PRODUCT_PRICE,
       MAX(IF (A.MARKET_ID = 6, A.LISTING_SKU, '')) AS MC_WALMART_LISTING_SKU,
       MAX(IF (A.MARKET_ID = 6, A.LISTING_ITEM_ID, '')) AS MC_WALMART_LISTING_ITEM_ID,
       MAX(IF (A.MARKET_ID = 6, A.LISTING_PRODUCT_NAME, '')) AS MC_WALMART_LISTING_PRODUCT_NAME,
       MAX(IF (A.MARKET_ID = 6, A.LISTING_PRODUCT_QTY, '')) AS MC_WALMART_LISTING_PRODUCT_QTY,
       MAX(IF (A.MARKET_ID = 6, A.LISTING_PRODUCT_PRICE, '')) AS MC_WALMART_LISTING_PRODUCT_PRICE,
       MAX(IF (A.MARKET_ID = 7, A.LISTING_SKU, '')) AS SKYHIGH_EBAY_LISTING_SKU,
       MAX(IF (A.MARKET_ID = 7, A.LISTING_ITEM_ID, '')) AS SKYHIGH_EBAY_LISTING_ITEM_ID,
       MAX(IF (A.MARKET_ID = 7, A.LISTING_PRODUCT_NAME, '')) AS SKYHIGH_EBAY_LISTING_PRODUCT_NAME,
       MAX(IF (A.MARKET_ID = 7, A.LISTING_PRODUCT_QTY, '')) AS SKYHIGH_EBAY_LISTING_PRODUCT_QTY,
       MAX(IF (A.MARKET_ID = 7, A.LISTING_PRODUCT_PRICE, '')) AS SKYHIGH_EBAY_LISTING_PRODUCT_PRICE,
       A.LISTING_PRODUCT_FBM
  FROM `LISTING` A
     , `INVENTORY` B
     , (SELECT MARKET_ID
             , CONCAT(BRAND_NAME, " ", CHANNEL_NAME) AS MARKET_NANE
          FROM `MARKET`) C
 WHERE A.STD_SKU   = B.STD_SKU
   AND A.MARKET_ID = C.MARKET_ID
 GROUP BY A.STD_SKU,
       B.PARENT_STD_SKU,
       B.PRODUCT_NAME,
       B.PRODUCT_SUPPLIER,
       B.PRODUCT_SIZE,
       B.PRODUCT_COLOR,
       B.PRODUCT_DESIGN