SELECT A.PRODUCT_CODE
     , A.STD_SKU
     , IF(LOCATE('_', REVERSE(B.PRODUCT_COLOR)) > 0, RIGHT(B.PRODUCT_COLOR, LOCATE('_', REVERSE(B.PRODUCT_COLOR)) - 1), B.PRODUCT_COLOR) AS PRODUCT_COLOR
     , B.SIZE_CODE
     , C.SHORT_SIZE_CODE
     , C.SIZE_ORDER
  FROM PRODUCT_MAP A
     , INVENTORY B
     , STD_SIZE C
 WHERE A.STD_SKU      = B.STD_SKU
   AND B.SIZE_CODE    = C.SIZE_CODE
 ORDER BY B.PRODUCT_COLOR
     , C.SIZE_ORDER