 SELECT IFNULL(A.BRAND_CODE, A.VENDOR_CODE)   AS VENDOR_CODE
      , IFNULL(AA.BRAND_NAME, BB.VENDOR_NAME) AS VENDOR_NAME
      , A.PRODUCT_CODE
      , B.PRODUCT_TITLE
      , C.PRODUCT_COLOR
      , D.SHORT_SIZE_CODE
      , D.SIZE_CODE
      , A.ORDER_QTY
   FROM PRODUCT_ORDER A
   LEFT OUTER JOIN BRAND AA
     ON (A.BRAND_CODE  = AA.BRAND_CODE)
   LEFT OUTER JOIN VENDOR BB
     ON (A.VENDOR_CODE = BB.VENDOR_CODE)
      , PRODUCT B
      , INVENTORY C
      , STD_SIZE D
  WHERE A.PRODUCT_CODE = B.PRODUCT_CODE
    AND A.STD_SKU      = C.STD_SKU
    AND C.SIZE_CODE    = D.SIZE_CODE
    AND A.ORDER_DATE   = ?
    AND A.ORDER_SEQ    = ?
  ORDER BY A.ORDER_DATE DESC
      , A.ORDER_SEQ DESC
      , A.STD_SKU