SELECT DISTINCT A.PRODUCT_CODE
     , B.SIZE_CODE
     , C.SHORT_SIZE_CODE
     , C.SIZE_ORDER
  FROM PRODUCT_MAP A
     , INVENTORY B
     , STD_SIZE C
 WHERE A.STD_SKU      = B.STD_SKU
   AND B.SIZE_CODE    = C.SIZE_CODE
   AND A.PRODUCT_CODE = ?
 ORDER BY C.SIZE_ORDER