SELECT B.PRODUCT_CODE
     , B.PRODUCT_TITLE
     , IFNULL(BB.MANUFACTURING_CODE, '') AS MANUFACTURING_CODE
     , B.BRAND_CODE
     , A.VENDOR_CODE
     , B.PACK_INFO
     , B.ORDER_BY_SIZE
  FROM VENDOR_MAP A
     , PRODUCT B
  LEFT OUTER JOIN (
      SELECT DISTINCT
             PRODUCT_CODE
           , MANUFACTURING_CODE
        FROM MANUFACTURING_MAP
      ) BB
    ON (B.PRODUCT_CODE = BB.PRODUCT_CODE)
 WHERE A.BRAND_CODE  = B.BRAND_CODE
   AND EXISTS (
     SELECT C.PRODUCT_CODE
       FROM PRODUCT_MAP C
      WHERE B.PRODUCT_CODE = C.PRODUCT_CODE
   )
 ORDER BY A.VENDOR_CODE
     , B.PRODUCT_CODE