SELECT A.STD_SKU
  FROM PRODUCT_MAP A
     , INVENTORY B
     , STD_SIZE C
 WHERE A.STD_SKU       = B.STD_SKU
   AND B.SIZE_CODE     = C.SIZE_CODE
   AND A.PRODUCT_CODE  = ?
   AND C.SIZE_CODE     = ?
   AND TRIM(SUBSTR(B.PRODUCT_COLOR FROM position('_' in B.PRODUCT_COLOR) + 1)) = ?