 SELECT A.ORDER_DATE
      , A.ORDER_SEQ
      , IFNULL(A.VENDOR_CODE, A.BRAND_CODE)    AS VENDOR_CODE
      , IFNULL(BB.VENDOR_NAME, AA.BRAND_NAME)  AS VENDOR_NAME
      , IFNULL(BB.VENDOR_EMAIL, AA.EMAIL)      AS VENDOR_EMAIL
      , IFNULL(BB.ORDERS_FROM, AA.ORDERS_FROM) AS ORDERS_FROM
      , A.BRAND_CODE
      , AA.BRAND_NAME
      , A.PRODUCT_CODE
      , B.PRODUCT_TITLE
      , C.PRODUCT_COLOR
      , D.SHORT_SIZE_CODE
      , D.SIZE_CODE
      , A.ORDER_QTY
      , A.EMPLOYEE_ID
      , TRIM(CONCAT(IFNULL(CC.FIRST_NAME, ' '), ' ', IFNULL(CC.LAST_NAME, ''))) AS EMPLOYEE_NAME
      , IFNULL(DD.MANUFACTURING_CODE, '')                                       AS MANUFACTURING_CODE
      , IFNULL(DD.MANUFACTURING_TITLE, '')                                      AS MANUFACTURING_TITLE
      , IFNULL(DD.MANUFACTURING_COLOR, '')                                      AS MANUFACTURING_COLOR
   FROM PRODUCT_ORDER A
   LEFT OUTER JOIN BRAND AA
     ON (A.BRAND_CODE  = AA.BRAND_CODE)
   LEFT OUTER JOIN VENDOR BB
     ON (A.VENDOR_CODE = BB.VENDOR_CODE)
   LEFT OUTER JOIN `USER` CC
     ON (A.EMPLOYEE_ID = CC.EMPLOYEE_ID)
   LEFT OUTER JOIN MANUFACTURING_MAP DD
     ON (A.PRODUCT_CODE = DD.PRODUCT_CODE
    AND A.STD_SKU       = DD.STD_SKU)
      , PRODUCT B
      , INVENTORY C
      , STD_SIZE D
  WHERE A.PRODUCT_CODE = B.PRODUCT_CODE
    AND A.STD_SKU      = C.STD_SKU
    AND C.SIZE_CODE    = D.SIZE_CODE    
    AND A.ORDER_DATE   = ?
    AND A.ORDER_SEQ    = ?
  ORDER BY A.ORDER_DATE DESC
      , A.ORDER_SEQ DESC
      , A.STD_SKU