SELECT A.PRODUCT_CODE
     , A.STD_SKU
     , B.PRODUCT_COLOR
     , B.SIZE_CODE
     , C.SHORT_SIZE_CODE
     , C.SIZE_ORDER
  FROM PRODUCT_MAP A
     , INVENTORY B
     , STD_SIZE C
 WHERE A.STD_SKU      = B.STD_SKU
   AND B.SIZE_CODE    = C.SIZE_CODE
   AND A.PRODUCT_CODE = ?
 ORDER BY B.PRODUCT_COLOR
     , C.SIZE_ORDER