SELECT B.PRODUCT_CODE
     , B.PRODUCT_TITLE
     , B.BRAND_CODE
     , B.PACK_INFO
     , B.ORDER_BY_SIZE
  FROM VENDOR_MAP A
     , PRODUCT B
 WHERE A.BRAND_CODE  = B.BRAND_CODE
   AND A.VENDOR_CODE = ?
   AND EXISTS (
     SELECT C.PRODUCT_CODE
       FROM PRODUCT_MAP C
      WHERE B.PRODUCT_CODE = C.PRODUCT_CODE
   )
 ORDER BY B.PRODUCT_CODE