SELECT A.PRODUCT_CODE
     , A.PRODUCT_TITLE
     , A.BRAND_CODE
     , A.PACK_INFO
     , A.ORDER_BY_SIZE
     , IFNULL(AA.MANUFACTURING_CODE, '') AS MANUFACTURING_CODE
  FROM PRODUCT A
  LEFT OUTER JOIN (
      SELECT DISTINCT
             PRODUCT_CODE
           , MANUFACTURING_CODE
        FROM MANUFACTURING_MAP
      ) AA
    ON (A.PRODUCT_CODE = AA.PRODUCT_CODE)
 WHERE EXISTS (
     SELECT B.PRODUCT_CODE
       FROM PRODUCT_MAP B
      WHERE A.PRODUCT_CODE = B.PRODUCT_CODE
   )
 ORDER BY A.PRODUCT_CODE